---
- name: Install Docker, Nginx, and Certbot
  hosts: all
  become: yes

  tasks:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Install Certbot and Nginx plugin
      ansible.builtin.apt:
        name: 
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Create cron job for Certbot auto-renewal
      cron:
        name: "Auto renew SSL certificates"
        job: "0 0 * * * /usr/bin/certbot renew --quiet && systemctl reload nginx"
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
